---
# ssh-keygen -t ecdsa -f ~/.ssh/id_ecdsa -N ""
# ANSIBLE_CONFIG=./ansible.cfg ansible all -m ansible.posix.authorized_key -b -K -k -u astra -a "key={{lookup('file','~/.ssh/id_ecdsa.pub')}} user=astra"
# ANSIBLE_CONFIG=./ansible.cfg ansible all -m lineinfile -a "path=/etc/sudoers \
# regexp='^%astra-admin\s+ALL=\(ALL:ALL\)\s+ALL' line='%astra-admin    ALL=(ALL:ALL) NOPASSWD: ALL'\
#  validate='/usr/sbin/visudo -cf %s'" --become -k -K
# ANSIBLE_CONFIG=./ansible.cfg ansible all -m ansible.builtin.shell -b -K -k \
#  -u astra -a "echo 'astra ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/astra && chmod 0440 /etc/sudoers.d/astra"
# sudo scp ./alse-gui-1.7.8-max-cloudinit-mg15.8.2-amd64.qcow2 192.168.50.159:~/
# ssh 192.168.50.159 sudo rsync -P alse-gui-1.7.8-max-cloudinit-mg15.8.2-amd64.qcow2 /var/lib/libvirt/images

- name: Настройка удалённых компьютеров для курса AP2301
  hosts: ap301_hosts
  become: true
  vars_files:
    - ./vars/vars.yaml
  tasks:

    # 1. Настройка репозиториев Astra Linux
    - name: Комментирование активных строк репозиториев
      ansible.builtin.shell: |
        sed -i '/^deb\s/s/^/#/' /etc/apt/sources.list

    - name: Добавление репозитория (main) через apt_repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.astralinux.ru/astra/frozen/1.8_x86-64/1.8.4/repository-main/ 1.8_x86-64 main contrib non-free non-free-firmware"
        state: present
        filename: repository-main
        update_cache: false

    - name: Добавление репозитория (extended) через apt_repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.astralinux.ru/astra/frozen/1.8_x86-64/1.8.4/repository-extended/ 1.8_x86-64 main contrib non-free non-free-firmware"
        state: present
        filename: repository-extended
        update_cache: false

    - name: Обновление кэша
      ansible.builtin.apt:
        update_cache: true

    # 2. Переключение режима Astra Linux в "Орёл" (отключение мандатного контроля)
    - name: Проверка текущего режима astra-modeswitch
      ansible.builtin.command: astra-modeswitch get
      register: modeswitch_status
      changed_when: false

    - name: Выполнение astra-modeswitch set 0
      ansible.builtin.command:
        cmd: /usr/sbin/astra-modeswitch set 0
      when: modeswitch_status.stdout | trim != '0'

    # 3. Установка необходимых пакетов
    - name: Установка пакетов (виртуализация, RDP, SSH, утилиты, Docker)
      ansible.builtin.apt:
        name:
          - astra-kvm
          - virt-manager
          - openssh-server
          - fly-dm-rdp
          - xrdp
          - git
          - mkisofs
          - docker.io
          - docker-compose-v2
        state: present
        install_recommends: true

    # 4. Добавление пользователя в группы
    - name: Добавление текущего пользователя в необходимые группы
      ansible.builtin.user:
        name: "{{ user }}"
        groups:
          - libvirt-admin
          - libvirt-qemu
          - libvirt
          - disk
          - kvm
          - astra-admin
          - astra-console
          - docker
        append: true

    # 5. Настройка firewalld (открытие портов и сервисов)
    - name: Запуск и включение firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Открытие сервисов rdp и ssh в firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - rdp
        - ssh

    - name: Открытие диапазона портов 5900-9000/tcp
      ansible.posix.firewalld:
        port: "5900-9000/tcp"
        permanent: true
        immediate: true
        state: enabled

    # 6. Настройка SSH-сервера (совместимость со старыми клиентами)
    - name: Создание каталога sshd_config.d
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        state: directory
        mode: '0755'

    - name: Добавление конфигурации для поддержки ssh-rsa
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/custom.conf
        content: |
          HostkeyAlgorithms +ssh-rsa
          PubkeyAcceptedKeyTypes +ssh-rsa
        owner: root
        group: root
        mode: '0644'
      notify: Restart ssh

    # 7.  ---- Настройка Tuned для производительности виртуализации ----
    - name: Проверка установки пакета tuned-ppd
      ansible.builtin.command: dpkg-query -W tuned-ppd
      register: tuned_ppd_pkg
      failed_when: false
      changed_when: false

    - name: Остановка и маскировка сервиса tuned-ppd (если есть)
      ansible.builtin.systemd:
        name: tuned-ppd
        state: stopped
        masked: true
      when: tuned_ppd_pkg.rc == 0

    - name: Установка пакета tuned
      ansible.builtin.apt:
        name: tuned
        state: present

    - name: Активация профиля virtual-host
      ansible.builtin.command: tuned-adm profile virtual-host
      register: tuned_profile
      changed_when: "'already used' not in tuned_profile.stdout"

    - name: Включение и запуск tuned
      ansible.builtin.systemd:
        name: tuned
        state: started
        enabled: true

    - name: Загрузка и проверка каждого qcow2 образа
      include_tasks: tasks/download_qcow2.yml
      with_items: "{{ alse_links }}"

    # 9. Добавление статических записей в /etc/hosts
    - name: Добавление записей в /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          10.0.1.11   dc-1.ald.company.lan         dc-1
          10.0.1.12   dc-2.ald.company.lan         dc-2
          10.0.1.51   pc-1.ald.company.lan         pc-1
          10.0.1.52   pc-2.ald.company.lan         pc-2
          10.0.1.26   file-1.ald.company.lan       file-1
          10.0.1.23   repo-1.ald.company.lan       repo-1
          10.0.1.25   cups-1.ald.company.lan       cups-1
          10.0.1.70   printer-1.ald.company.lan    printer-1
          10.0.1.30   dhcp-1.ald.company.lan       dhcp-1
          10.0.1.33   pxe-1.ald.company.lan        pxe-1
          10.0.1.21   monitoring-1.ald.company.lan monitoring-1
          10.0.1.22   audit-1.ald.company.lan      audit-1
          10.0.1.55   pc-5.ald.company.lan         pc-5
          10.0.1.56   pc-6.ald.company.lan         pc-6
          10.0.1.99   exam-client.ald.company.lan  exam-client
          10.0.1.101  windc-1.win.company.lan      windc-1
          10.0.1.102  winpc-1.win.company.lan      winpc-1
        marker: "# {mark} ANSIBLE MANAGED BLOCK - ASTRA HOSTS"
        insertafter: EOF
        state: present

  handlers:
    - name: Restart ssh
      ansible.builtin.systemd:
        name: ssh
        state: restarted


- name: Установка terragrunt и terraform
  hosts: ap301_hosts
  become: false
  vars_files:
    - ./vars/vars.yaml
  tasks:
    # 10. Настройка PATH и переменной LIBVIRT_DEFAULT_URI в .bashrc
    - name: Добавление ~/.local/bin в PATH
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: 'export PATH=${PATH}:${HOME}/.local/bin'
        regexp: '^export PATH=.*\.local/bin'
        state: present

    - name: Добавление LIBVIRT_DEFAULT_URI
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.bashrc"
        line: 'export LIBVIRT_DEFAULT_URI="qemu:///system"'
        regexp: '^export LIBVIRT_DEFAULT_URI='
        state: present

    # ---- Генерация SSH-ключа ECDSA (если отсутствует) ----
    - name: Создание каталога .ssh (если не существует)
      ansible.builtin.file:
        path: "{{ home_dir }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Генерация SSH-ключа ECDSA (без пароля)
      ansible.builtin.command: ssh-keygen -t ecdsa -f {{ home_dir }}/.ssh/id_ecdsa -N ""
      args:
        creates: "{{ home_dir }}/.ssh/id_ecdsa"

    # ---- Проверка наличия Terraform ----
    - name: Проверка существования исполняемого файла terraform (желтый цвет, если отсутствует)
      ansible.builtin.stat:
        path: "{{ home_dir }}/.local/bin/terraform"
      register: terraform_bin
      changed_when: not terraform_bin.stat.exists

    - name: Установка Terraform (если отсутствует)
      ansible.builtin.import_tasks: tasks/install_terraform.yml
      when: not terraform_bin.stat.exists

    # ---- Проверка наличия Terragrunt ----
    - name: Проверка существования исполняемого файла terragrunt (желтый цвет, если отсутствует)
      ansible.builtin.stat:
        path: "{{ home_dir }}/.local/bin/terragrunt"
      register: terragrunt_bin
      changed_when: not terragrunt_bin.stat.exists

    - name: Установка Terragrunt (если отсутствует)
      ansible.builtin.import_tasks: tasks/install_terragrunt.yml
      when: not terragrunt_bin.stat.exists
